version: '3.3'
services:
  app:
    image: ${DOCKER_IMAGE}
    build: ..
    restart: always
    ports:
      - 4500:8000
    environment:
      - ISSUE_BACKEND
      - ISSUE_BACKEND_API_KEY
      - ISSUE_BACKEND_USER
      - ISSUE_BACKEND_REPO
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
